### ISSUE TITLE
untappedVintage Wiki (design docs) checklist

### ISSUE THREAD

**Issue by siascone** [HelenEdwards/untappedVintage#1]
# Wiki Home Page
- [x] Is the first page you see upon entering the wiki
- [x] Contains a welcome message
- [x] Contains a link/placeholder for a link to the live page
- [x] All links in the right sidebar should contain each wiki page and link to the correct page
- [x] Correctly formatted
  - [x] each wiki page is listed in bullet points
  - [x] all links route the correct page

---

# MVP List
- [x] Should have 7 MVPs.
  - [x] 3 of those are User Auth, Heroku, and Production README.
  - [x] The other 4 are from the [MVP List](https://github.com/appacademy/curriculum/blob/master/full-stack-project/proposal/mvp-list.md) or they have clarified them with you
- [x] Contains a description sentence of the app
- [x] Includes two to three detailed bullets on functionality and presentation of feature
- [x] At least one CRUD feature, which states what CRUD operations are planned (creation, reading, updating, deletion)
- [x] Estimates how long it will take the code each MVP
- [x] Correctly formatted
  - [x] MVPs are listed in an ordered list
  - [x] Each MVP is broken down into bullet points

---

# Database Schema
- [x] Contains correct datatypes
- [x] Contains appropriate constraints/details
  - [x] primary key
  - [x] not null
  - [x] unique
  - [x] indexed
  - [x] foreign key
- [x] Contains bullet points after the table that state which foreign keys will reference to which table, or references to the associations which will be made
 - [x] foreign key and table name are lowercased, snake_cased and `back_ticked`
- [x] Correctly formatted
  - [x] schema is written in a table format
  - [x] the table’s name are lowercased, snake_cased and `back_ticked`
  - [x] the table header column names are bolded
  - [x] columns names are lowercased and snaked_cased and `back_ticked`

---

# Sample State
- [x] State shape is flat!
- [x] State’s keys are camelCased
- [x] All keys within the values in the state are accessible in the schema
- [x] Correctly formatted
  - [x] Sample state is rendered with triple backticks, and the language ` ```javascript...``` `). This will display the state as a code block instead of a giant line of text 
  - [x] Top level slices
    - [x] `entities`
    - [x] `session`
    - [x] `errors` (here or in `ui`)
    - [x] `ui` (if needed)
  - [x] Should NOT have nested slices, aka `comments` inside of `posts`
   + Some info from other tables is ok, for instance:
    + the author username and imageurl for a post. basically any info that the user can’t change
    + like count and a boolean on whether the user likes the post instead of a likes slice

---

# Backend Routes
- [x] Contains the following sections: HTML, API Endpoints(Backend)
- [x] Each route has a description
- [x] API Endpoint routes contains wildcard variables written in `snake_case`
- [x] Routes does not contain [superfluous routes](https://github.com/appacademy/curriculum/blob/master/rails/readings/routing-part-ii.md)
- [x] Have API routes that will allow the front end to get all info it needs and does not have unneeded routes:
  + probably doesn’t need a `GET likes` api endpoint because that info comes through the post show

---

# Frontend Routes
- [x] Frontend routes contains wildcard variables written in `camelCase`
- [x] Correctly formatted
  - [x] Routes are displayed with `inline coding text` (backticks)

**Comment by siascone** [comment]
Great job, your design docs are coming along nicely. Take a look at the remaining items/edits left in the check list. If you have any questions let me know.

Additional Notes (typos, suggestions, etc):
- MVPs
  - Extra 7th MVP, remove or make 8th
  - Add estimated number of days to each mvp heading (ex: Drinks CRUD (1/28/22, 2 Days))

- Database Schema
  - the table’s name should lowercased, snake_cased and back_ticked
  - the column names should be lowercased and snaked_cased and back_ticked
  - missing bullets detailing table references (associations) and index on columns. Check out the blue bird [wiki](https://github.com/appacademy/bluebird/wiki/schema) for reference.

- Sample State
  - missing commas after closing curly brace for beer and brewery
  - beer and brewery should probably be beers and breweries
  - keys should be camelCased not snake_cased (ex: flavorProfiles)

- Backend Routes
  - Users edit route should be `PATCH /api/user/:id`
  - breweries post route has an extra backtick after the T in POST
  - make route description dash the same across all routes (- or -> but not both).
  - wildcards should be data specific and snake cased (ex: api/review/review_id, api/users/user_id etc)

**Comment by siascone** [comment]
Your edits are looking good. Just a few more things to add:

Wiki Home
- add a live link placeholder to your wiki home page (ex: [Live Link](#))
  - ``` [Live Link](#) ``` <-- code block showing markdown for placeholder link

Schema
- add a joins table to join the flavor_profiles and beers tables creating a many to many relationship so you don't have to store flavor_profiles ids as an array in your beers table.
- add backtics to table names and column names (ex: `beers`, `id`, `name`, `serving_style` etc.)
- Update/remove long notes about flavor profiles once you have the flavors joins table set up.

Backend Routes
- Add ':' to wildcards (ex: api/review/:review_id)

Frontend Routes
- one key still snake_cased, should be camelCased (flavorProfiles)

**Comment by siascone** [comment]
Just took another look. Everthing looks great. Remember to add "foreign key" to your details of the beer_flavor_profiles table for columns beer_id and flavor_profile_id
